### PR TITLE
Added support for SBOLDocument as well as filename for BOOST APIs

### PR DESCRIPTION
**Pull request by Prem0707**

### CODE REVIEW

**Comment by Prem0707** [comment]
Ernst, Please test it once before merging to GSoC18 branch

**Comment by Prem0707** [comment]
While testing, I am getting a response like:  Job is not finished yet (on printing the response)

Is the BOOST_REST_URL = "https://boost.jgi.doe.gov/Dev/rest" is up and running?

**Comment by eoberortner** [comment]
Prem,

things work well at my end using the https://boost.jgi.doe.gov/Dev/rest <https://boost.jgi.doe.gov/Dev/rest> endpoint.
please find attached the JSON of the finished job. 

at the end of the DemoClient’s main() method, there’s a nested loop iterating over all submitted jobs and waiting for each job to be finished.
There’s a 
System.out.println("Job " + jobUUID + " is not finished yet.");
command.
Did you wait until the job is finished?

Thanks,
Ernst

**Comment by Prem0707** [comment]
There might be the issue with my internet connection. I was getting the same message again and again. 

Please merge it to GSoC18 branch if it is working at your end. Thanks

**Comment by Prem0707** [comment]
Have you updated the backend for the CodonJuggling method? As per my task, I am planning to work to draw the response returned by it on DBOLDesigner.

**Comment by eoberortner** [comment]
OK, my up-to-date code is in the repo under the GSoC18 branch now.
please let me know if you run into any issues!

**Comment by eoberortner** [comment]
apologies! I wasn’t able to update the BOOST back-end yet. 
At the moment, you have to read the modified sequence from the returned SBOLDocument.

**Comment by Prem0707** [comment]
Ok, No problem with that, Here are the steps, as per I think, I need to follow in order to draw it in SBOLDesigner:
1. During sending the current design as a SBOLDocument to BOOST APIs, I can store that document into temporary memory
2. Make the API call and get the response from BOOST backend
3. Parse out the modified sequence from returned document (by BOOST)
4. Remove the original sequence from initial SBOLDocument and fill out the space of sequence with the modified one.
5 Open this into the designer.

Is this work or anything else I should follow for now? Thanks

**Comment by eoberortner** [comment]
Prem, this sounds great!
Please, can you share the steps with Chris and Michael too? 
I’m not sure if they are following this thread and they may have some input regarding how things need to be handled at the SBOLDesigner side.

Thanks!

**Pull request merged**
